// Generated by tool/gen_brand.py, which builds every logo file from the
// same numbers. Don't edit by hand: change the generator and run it again.

import 'dart:ui';

/// The logo's colourways. [volt] is the primary one (launcher icon, splash
/// and store); the others can be picked in You > Logo.
enum BrandLogo {
  volt(
    bg: Color(0xFF0E0F11),
    plate: Color(0xFFF5F5F4),
    accent: Color(0xFFC6F432),
  ),
  ember(
    bg: Color(0xFF15110F),
    plate: Color(0xFFF4EFE9),
    accent: Color(0xFFFF5A26),
  ),
  chalk(
    bg: Color(0xFFF1EEE7),
    plate: Color(0xFF15110F),
    accent: Color(0xFFFF5A26),
  );

  new({required this.bg, required this.plate, required this.accent});

  /// The tile behind the mark.
  final Color bg;

  /// Every plate of the stack but one.
  final Color plate;

  /// The one coloured plate: "your level" on the stack.
  final Color accent;
}

/// The Weight Stack R: an R built from the plates of a weight stack, on a
/// [width] x [height] grid.
abstract final class BrandGeometry {
  static const double width = 160;
  static const double height = 192;
  static const double plateHeight = 32;
  static const double plateRadius = 4;

  /// How tall the mark is on its tile, as a share of the tile.
  static const double tileShare = 0.47;

  /// Corner radius of the tile, as a share of its size.
  static const double tileRadius = 0.22;

  /// Left edge, top edge and width of each plate.
  static const plates = <({double x, double y, double width, bool accent})>[
    (x: 0, y: 0, width: 144, accent: false),
    (x: 0, y: 40, width: 56, accent: false),
    (x: 104, y: 40, width: 56, accent: false),
    (x: 0, y: 80, width: 144, accent: true),
    (x: 0, y: 120, width: 56, accent: false),
    (x: 72, y: 120, width: 56, accent: false),
    (x: 0, y: 160, width: 56, accent: false),
    (x: 104, y: 160, width: 56, accent: false),
  ];
}
