import 'dart:convert';
import 'dart:io';

import 'package:ripped/domain/catalog/exercise.dart';
import 'package:sqlite3/sqlite3.dart';

/// Reads the bundled read-only catalog (generated by tool/build_catalog)
/// fully into memory. ~200 rows: loading once beats querying per screen.
abstract final class CatalogLoader {
  static List<Exercise> loadFile(File file) {
    final db = sqlite3.open(file.path, mode: OpenMode.readOnly);
    try {
      return load(db);
    } finally {
      db.close();
    }
  }

  static List<Exercise> load(Database db) {
    final subs = <String, List<String>>{};
    for (final r in db.select(
      'SELECT exercise_id, substitute_id FROM exercise_substitutes '
      'ORDER BY exercise_id, rank',
    )) {
      (subs[r['exercise_id'] as String] ??= []).add(
        r['substitute_id'] as String,
      );
    }

    return [
      for (final r in db.select('SELECT * FROM exercises ORDER BY id'))
        Exercise(
          id: r['id'] as String,
          name: r['name'] as String,
          pattern: MovementPattern.parse(r['pattern'] as String),
          equipment: Equipment.fromCatalog(r['equipment'] as String),
          equipmentLabel: r['equipment'] as String,
          level: Level.parse(r['level'] as String),
          priority: r['priority'] as int,
          primaryMuscles: _strings(r['primary_muscles']),
          secondaryMuscles: _strings(r['secondary_muscles']),
          jointStress: {
            for (final j in _strings(r['joint_stress'])) Joint.parse(j),
          },
          isBodyweight: r['is_bodyweight'] == 1,
          unilateral: r['unilateral'] == 1,
          isTimed: r['is_timed'] == 1,
          instructions: _strings(r['instructions']),
          media: [
            for (final m in (jsonDecode(
              r['media'] as String,
            ) as List).cast<Map<String, dynamic>>())
              ExerciseMedia(
                kind: MediaKind.values.byName(m['kind'] as String),
                uri: m['uri'] as String,
                license: m['license'] as String,
                attribution: m['attribution'] as String,
              ),
          ],
          substitutes: subs[r['id']] ?? const [],
        ),
    ];
  }

  static List<String> _strings(Object? json) =>
      (jsonDecode(json! as String) as List).cast<String>();
}
